# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statistique.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

try:
    from pyqtgraph import PlotWidget
except ModuleNotFoundError:
    import os 
    os.system("pip install pyqtgraph")
    from pyqtgraph import PlotWidget
import numpy as np

class Ui_Statistique(object):
    def setupUi(self, Statistique):
        Statistique.setObjectName("Statistique")
        Statistique.setWindowModality(QtCore.Qt.ApplicationModal)
        Statistique.resize(752, 566)
        Statistique.setMinimumSize(QtCore.QSize(752, 566))
        Statistique.setFixedWidth(752)
        Statistique.setFixedHeight(566)
        self.ExportButton = QtWidgets.QPushButton(Statistique)
        self.ExportButton.setGeometry(QtCore.QRect(210, 500, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(14)
        self.ExportButton.setFont(font)
        self.ExportButton.setObjectName("ExportButton")
        self.RetourButton = QtWidgets.QPushButton(Statistique)
        self.RetourButton.setGeometry(QtCore.QRect(410, 500, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(14)
        self.RetourButton.setFont(font)
        self.RetourButton.setObjectName("RetourButton")

        self.graphicsView = PlotWidget(Statistique)
        self.graphicsView.setGeometry(QtCore.QRect(35, 11, 691, 471))
        self.graphicsView.setObjectName("graphicsView")
        
        self.retranslateUi(Statistique)
        QtCore.QMetaObject.connectSlotsByName(Statistique)
    def retranslateUi(self, Statistique):
        _translate = QtCore.QCoreApplication.translate
        Statistique.setWindowTitle(_translate("Statistique", "Form"))
        self.ExportButton.setText(_translate("Statistique", "Exporter"))
        self.RetourButton.setText(_translate("Statistique", "Retour"))


